mysite/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'

urlpatterns = [

    path('', views.CatList.as_view(), name='all'),
    path('main/<int:pk>/detail', views.CatDetail.as_view(), name = 'cat_detail'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('breed/', views.BreedList.as_view(), name='breedlist'),
    path('breed/main/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('breed/main/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('breed/main/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),

]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView
# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('hello/',include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('cats/',include('cats.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),

    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(max_length=200,validators=[MinLengthValidator(2, "Breed must be greater than 1 character")])
    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(max_length=200,validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")])
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)
    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Cat, Breed

# Create your views here.
class CatList(LoginRequiredMixin, ListView):
    model = Cat
    template_name = 'cats/cat_list.html' # <app_name>/blog_list.html
    context_object_name = 'object_list' # Default is object_list if not specified

class CatDetail(LoginRequiredMixin, DetailView):
    model = Cat
    template_name = 'cats/cat_detail.html' # <app_name>/blog_list.html
    context_object_name = 'object_list' # Default is object_list if not specified

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedList(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'cats/breed_list.html' # <app_name>/blog_list.html
    context_object_name = 'object_list' # Default is object_list if not specified

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breedlist')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breedlist')

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breedlist')

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Breed</h1>
<p>Are you sure you want to delete the breed: {{Breed}}?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:breedlist' %}' ; return false;" value="Cancel">
</form>
{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}
{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>

{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Breed List</title>
</head>
<body>
    <h1>Breed List</h1>
    <ul>
        {% if object_list %}
        {% for breed in object_list %}
<li> {{breed.name }} <a href="{% url 'cats:breed_update' breed.pk %}">(Update</a> <a href= "{% url 'cats:breed_delete' breed.pk %}">| Delete)</a></li>
        {% endfor %}
        {% else %}
        <p> No Breeds </p>
        {% endif %}
    </ul>
    <a href = "{% url 'cats:breed_create' %}">  Create Breeds </a> | <a href = "{% url 'cats:all' %}"> Cat List </a>
</body>
</html>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Make</h1>
<p>Are you sure you want to delete the cat: {{Cat}}?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>
{% endblock %}

mysite/cats/templates/cats/cat_detail.html
{% extends "base_bootstrap.html" %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object_list.nickname }}</title>
</head>
<body>
    <h1> Cat Detail</h1>
    <p>Nickname: {{ object_list.weight }}</p>
   <p>Foods: {{object_list.foods}} </p>
    <p>Author: {{ object_list.breed}}</p>

    <a href="{% url 'cats:all' %}">Back to Cat List</a>
</body>
</html>
{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cat List</title>
</head>
<body>
    <h1>Cat List</h1>
    <ul>
        {% if object_list %}
        {% for cat in object_list %}
    <li> <a href="{% url 'cats:cat_detail' cat.pk %}">{{cat.nickname }}</a>  <a href="{% url 'cats:cat_update' cat.pk %}">(Update</a> |
     <a href="{% url 'cats:cat_delete' cat.pk %}"> Delete)</a></li>
        {% endfor %}
        {% else %}
        <p> No Cats </p>
        {% endif %}
    </ul>
     <a href = "{% url 'cats:cat_create' %}"> Create Cats </a> | <a href = "{% url 'cats:breedlist' %}"> Show Breeds </a>
</body>
</html>
{% endblock %}